# **Numpy(Basics)**

In [ ]:
#Creating and modifying an array
arr=[10,20,30,50,70]
print("Array= ",arr)
arr.append(80)
arr[3]=55
arr.remove(30)
print("Modifying Array: ",arr)

Array=  [10, 20, 30, 50, 70]
Modifying Array:  [10, 20, 55, 70, 80]


In [ ]:
#Finding Min,Max and Mean
import numpy as np
arr=np.array([10,50,40,70,80,320])
print("Minimum Value: ",np.min(arr))
print("Maximum Value: ",np.max(arr))
print("Mean Value: ",np.mean(arr))

Minimum Value:  10
Maximum Value:  320
Mean Value:  95.0


In [ ]:
#Reshaping and flattening an array
import numpy as np
arr = np.array([10,23,36,45,58,61])
reshaped=arr.reshape(2, 3)
print(reshaped)
flattened=reshaped.flatten()
print(flattened)

[[10 23 36]
 [45 58 61]]
[10 23 36 45 58 61]


In [ ]:
#create 2*2 arrays and stack them vertical and horizontal
import numpy as np
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
vertical= np.vstack((arr1, arr2))
horizontal= np.hstack((arr1, arr2))
print("\nArray 1:\n", arr1)
print("\nArray 2:\n", arr2)
print("\nVertically Stacked:\n", vertical)
print("\nHorizontally Stacked:\n", horizontal)


Array 1:
 [[1 2]
 [3 4]]

Array 2:
 [[5 6]
 [7 8]]

Vertically Stacked:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontally Stacked:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Convert 1D array of size 9 into 3*3 matrix
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
matrix=arr.reshape(3, 3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#create array from 1 to 10 & reverse it
import numpy as np
arr = np.arange(1, 11)
reverse= arr[::-1]
print("Original Array:",arr)
print("Reversed Array:",reverse)

Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Reversed Array: [10  9  8  7  6  5  4  3  2  1]
