In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from google.colab import files

In [41]:
from google.colab import files
uploaded = files.upload()

Saving insurances.csv to insurances.csv


In [43]:
df = pd.read_csv('insurances.csv')
df.dropna(inplace =True)
print(df.head())
print(df.info())

   age     sex   bmi  children  expenses
0   19  female  27.9         0  16884.92
1   18    male  33.8         1   1725.55
2   28    male  33.0         3   4449.46
3   33    male  22.7         0  21984.47
4   32    male  28.9         0   3866.86
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   expenses  1338 non-null   float64
dtypes: float64(2), int64(2), object(1)
memory usage: 52.4+ KB
None


In [44]:
df = np.array(df)
X = df[:,2:]
print(X)

[[27.9 0 16884.92]
 [33.8 1 1725.55]
 [33.0 3 4449.46]
 ...
 [36.9 0 1629.83]
 [25.8 0 2007.95]
 [29.1 0 29141.36]]


In [56]:
Y = df[:,1]
print(Y)

['female' 'male' 'male' ... 'female' 'female' 'female']


In [57]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=7)
print(X_test)

[[39.8 0 11090.72]
 [29.8 1 9288.03]
 [16.0 0 1694.8]
 [18.3 5 19023.26]
 [24.3 0 9863.47]
 [29.0 0 1906.36]
 [19.3 0 15820.7]
 [27.9 3 18838.7]
 [27.9 0 2867.12]
 [35.3 0 7348.14]
 [34.2 0 3935.18]
 [38.0 3 6196.45]
 [23.8 0 2395.17]
 [30.6 0 2459.72]
 [32.1 1 11763.0]
 [35.9 1 26392.26]
 [31.4 1 3659.35]
 [41.5 0 13405.39]
 [20.1 1 12032.33]
 [29.7 0 7789.64]
 [32.9 2 5375.04]
 [23.7 0 2352.97]
 [36.4 1 51194.56]
 [26.7 2 22478.6]
 [24.8 0 17904.53]
 [28.1 1 22331.57]
 [34.2 2 44260.75]
 [40.2 0 38126.25]
 [31.6 1 7358.18]
 [34.1 1 6600.21]
 [31.2 1 10461.98]
 [20.0 0 22412.65]
 [32.8 1 14358.36]
 [34.9 0 11944.59]
 [23.2 0 11830.61]
 [34.4 0 1137.47]
 [24.3 5 5615.37]
 [42.4 1 3410.32]
 [34.3 3 9563.03]
 [22.0 1 1964.78]
 [33.6 2 3579.83]
 [28.3 1 4779.6]
 [27.5 1 7626.99]
 [34.2 1 6289.75]
 [29.0 1 7050.64]
 [20.2 2 4906.41]
 [32.5 1 3490.55]
 [38.1 2 42560.43]
 [25.3 1 21771.34]
 [34.3 2 13224.06]
 [23.6 1 8539.67]
 [20.1 2 18767.74]
 [38.1 2 24915.05]
 [26.6 2 9715.84]
 [35.2 0 2

In [58]:
clf = KNeighborsClassifier()
clf.fit(X_train,Y_train)

KNeighborsClassifier()

In [48]:
score = clf.score(X_train,Y_train)
print("Training Accuracy:", score)
test_score = clf.score(X_test, Y_test)
print("Test Accuracy:", test_score)

Training Accuracy: 0.7663551401869159
Test Accuracy: 0.6380597014925373


In [49]:
predictions = clf.predict(X_test)
print(predictions)

['female' 'male' 'male' 'male' 'female' 'female' 'female' 'female'
 'female' 'female' 'female' 'female' 'male' 'female' 'male' 'male' 'male'
 'female' 'female' 'male' 'female' 'male' 'male' 'male' 'female' 'male'
 'male' 'male' 'female' 'male' 'male' 'male' 'female' 'male' 'female'
 'male' 'female' 'female' 'female' 'male' 'female' 'male' 'female' 'male'
 'female' 'female' 'male' 'male' 'female' 'female' 'female' 'female'
 'female' 'female' 'female' 'male' 'female' 'female' 'male' 'female'
 'male' 'female' 'male' 'female' 'female' 'male' 'male' 'male' 'male'
 'male' 'female' 'female' 'female' 'female' 'female' 'female' 'male'
 'female' 'female' 'female' 'female' 'male' 'male' 'female' 'male' 'male'
 'male' 'female' 'female' 'male' 'male' 'female' 'male' 'male' 'female'
 'female' 'female' 'female' 'male' 'male' 'male' 'female' 'female'
 'female' 'male' 'female' 'female' 'female' 'female' 'male' 'male'
 'female' 'male' 'female' 'male' 'female' 'female' 'male' 'female' 'male'
 'female' 'f

In [50]:
print(X_test.shape)

(268, 3)


In [51]:
predict = clf.predict(X_test)
print(accuracy_score(Y_test, predict))

0.6380597014925373
