In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from google.colab import files

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Age-standardized suicide rates.csv to Age-standardized suicide rates.csv


In [ ]:
df = pd.read_csv('Age-standardized suicide rates.csv')
df.dropna(inplace =True)
print(df.head())
print("Type of df:", type(df))

       Country          Sex  2016  2015  2010  2000
0  Afghanistan   Both sexes   6.4   6.6   7.4   8.1
1  Afghanistan         Male  10.6  10.9  12.5  14.3
2  Afghanistan       Female   2.1   2.1   2.1   1.7
3      Albania   Both sexes   5.6   5.3   7.7   5.8
4      Albania         Male   7.0   6.7   9.5   8.2
Type of df: <class 'pandas.core.frame.DataFrame'>


In [ ]:
df = np.array(df)
X = df[:,2:]
print(X)

[[6.4 6.6 7.4 8.1]
 [10.6 10.9 12.5 14.3]
 [2.1 2.1 2.1 1.7]
 ...
 [19.1 18.9 20.6 21.7]
 [29.1 28.7 32.3 35.5]
 [11.1 11.1 11.1 9.8]]


In [ ]:
Y = df[:,1]
print(Y)

[' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' 

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=7)
print(X_test)

[[6.2 6.6 7.8 10.6]
 [4.6 4.5 4.6 4.4]
 [19.4 19.8 22.7 24.3]
 [19.1 18.9 20.6 21.7]
 [6.2 6.1 5.6 5.1]
 [5.2 5.4 5.5 6.5]
 [7.6 6.7 9.1 11.7]
 [5.7 5.9 6.8 5.9]
 [5.6 5.3 7.7 5.8]
 [14.5 14.7 15.1 16.1]
 [15.8 16.1 15.9 24.7]
 [4.7 4.8 5.4 6.6]
 [8.7 8.7 9.0 10.4]
 [1.1 1.1 1.1 0.8]
 [3.8 4.1 4.5 3.1]
 [7.9 7.7 8.3 9.4]
 [21.4 21.7 21.0 23.7]
 [15.0 17.4 15.3 20.6]
 [8.1 8.0 7.9 7.9]
 [24.8 25.3 20.2 24.4]
 [11.9 11.9 12.4 18.3]
 [3.1 3.1 4.1 8.2]
 [8.4 8.2 8.3 9.0]
 [5.8 5.7 5.2 8.2]
 [13.8 14.1 14.4 19.8]
 [32.0 31.9 29.1 23.1]
 [0.9 1.1 0.6 0.9]
 [8.1 8.3 9.1 12.3]
 [7.2 7.2 8.1 7.3]
 [17.1 17.1 16.4 15.3]
 [17.5 17.2 16.1 16.0]
 [2.0 2.1 2.3 2.4]
 [8.6 8.6 8.8 5.3]
 [11.9 11.6 10.6 12.7]
 [3.4 3.4 2.9 2.7]
 [4.6 4.5 3.3 4.5]
 [32.6 32.1 31.0 30.2]
 [12.6 12.3 12.9 13.6]
 [17.6 17.6 17.5 13.6]
 [6.0 6.2 5.3 5.4]
 [3.8 3.8 4.2 2.1]
 [12.8 12.8 14.5 13.9]
 [4.6 4.6 5.4 5.0]
 [0.9 0.9 0.9 0.8]
 [3.7 3.8 4.7 8.3]
 [10.5 10.7 11.2 10.6]
 [0.0 0.0 0.5 4.3]
 [1.9 1.9 1.6 1.8]
 [12.2 12.2 

In [ ]:
clf = KNeighborsClassifier()
clf.fit(X_train,Y_train)

KNeighborsClassifier()

In [ ]:
score = clf.score(X_train,Y_train)
print("Training Accuracy:", score)
test_score = clf.score(X_test, Y_test)
print("Test Accuracy:", test_score)

Training Accuracy: 0.6651480637813212
Test Accuracy: 0.5454545454545454


In [ ]:
predictions = clf.predict(X_test)
print(predictions)

[' Female' ' Female' ' Male' ' Male' ' Both sexes' ' Male' ' Both sexes'
 ' Female' ' Female' ' Male' ' Male' ' Male' ' Male' ' Female'
 ' Both sexes' ' Both sexes' ' Male' ' Both sexes' ' Both sexes' ' Male'
 ' Both sexes' ' Female' ' Female' ' Both sexes' ' Male' ' Male' ' Female'
 ' Both sexes' ' Both sexes' ' Male' ' Both sexes' ' Female' ' Both sexes'
 ' Both sexes' ' Both sexes' ' Both sexes' ' Male' ' Both sexes'
 ' Both sexes' ' Both sexes' ' Both sexes' ' Both sexes' ' Male' ' Female'
 ' Female' ' Both sexes' ' Both sexes' ' Female' ' Male' ' Both sexes'
 ' Female' ' Male' ' Both sexes' ' Female' ' Both sexes' ' Female' ' Male'
 ' Both sexes' ' Both sexes' ' Both sexes' ' Both sexes' ' Both sexes'
 ' Male' ' Female' ' Male' ' Both sexes' ' Male' ' Female' ' Female'
 ' Both sexes' ' Female' ' Male' ' Female' ' Both sexes' ' Both sexes'
 ' Both sexes' ' Both sexes' ' Female' ' Female' ' Both sexes'
 ' Both sexes' ' Both sexes' ' Both sexes' ' Both sexes' ' Both sexes'
 ' Female'

In [ ]:
print(X_test.shape)

(110, 4)


In [ ]:
predict = clf.predict(X_test)
print(accuracy_score(Y_test, predict))

0.5454545454545454
