In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder

In [3]:
from google.colab import files
uploaded = files.upload()

Saving sample_facilities.csv to sample_facilities.csv


In [4]:
df = pd.read_csv('sample_facilities.csv')
df.dropna(inplace =True)
print(df.head(10))

        Country  Year  Mental_Hospitals  Health_Units  Outpatient_Facilities  \
0           USA  2020               1.2           2.3                    3.1   
1         India  2019               0.8           1.5                    2.4   
2            UK  2018               1.1           2.0                    2.9   
3       Germany  2021               1.3           2.5                    3.3   
4        Canada  2017               0.9           1.7                    2.1   
5        France  2016               1.0           1.9                    2.5   
6     Australia  2022               1.4           2.6                    3.5   
7         Japan  2023               1.5           2.8                    3.7   
8        Brazil  2020               0.7           1.2                    1.8   
9  South Africa  2018               0.6           1.1                    1.6   

   Day_Treatment  Residential_Facilities  
0            0.5                     1.0  
1            0.3                 

In [5]:
df.describe()

Year  Mental_Hospitals  Health_Units  Outpatient_Facilities  \
count    10.000000         10.000000     10.000000              10.000000   
mean   2019.400000          1.050000      1.960000               2.690000   
std       2.221111          0.302765      0.589161               0.723341   
min    2016.000000          0.600000      1.100000               1.600000   
25%    2018.000000          0.825000      1.550000               2.175000   
50%    2019.500000          1.050000      1.950000               2.700000   
75%    2020.750000          1.275000      2.450000               3.250000   
max    2023.000000          1.500000      2.800000               3.700000   

       Day_Treatment  Residential_Facilities  
count      10.000000               10.000000  
mean        0.410000                0.850000  
std         0.233095                0.302765  
min         0.100000                0.400000  
25%         0.225000                0.625000  
50%         0.350000                0.850000  
75%         0.575000                1.075000  
max         0.800000                1.300000

In [ ]:
df = np.array(df)
X = df[:, 2:]
print(X)

[[1.2 2.3 3.1 0.5 1.0]
 [0.8 1.5 2.4 0.3 0.7]
 [1.1 2.0 2.9 0.4 0.9]
 [1.3 2.5 3.3 0.6 1.1]
 [0.9 1.7 2.1 0.2 0.6]
 [1.0 1.9 2.5 0.3 0.8]
 [1.4 2.6 3.5 0.7 1.2]
 [1.5 2.8 3.7 0.8 1.3]
 [0.7 1.2 1.8 0.1 0.5]
 [0.6 1.1 1.6 0.2 0.4]]


In [ ]:
Y = df[:, 3]
print(Y)

[2.3 1.5 2.0 2.5 1.7 1.9 2.6 2.8 1.2 1.1]


In [ ]:
Y = LabelEncoder().fit_transform(Y.astype(str))
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=7)
print(X_test)

[[0.7 1.2 1.8 0.1 0.5]
 [1.0 1.9 2.5 0.3 0.8]]


In [ ]:
clf = SVC(kernel="linear", C=1, class_weight="balanced")
clf.fit(X_train, Y_train)

SVC(C=1, class_weight='balanced', kernel='linear')

In [ ]:
print(X_train.shape)
print(X_train[:5])

(8, 5)
[[1.2 2.3 3.1 0.5 1.0]
 [1.1 2.0 2.9 0.4 0.9]
 [0.8 1.5 2.4 0.3 0.7]
 [0.6 1.1 1.6 0.2 0.4]
 [1.5 2.8 3.7 0.8 1.3]]


In [ ]:
clf.fit(X_train, Y_train)
prediction = clf.predict([[1.5, 2.8, 3.7, 0.8, 1.3]])

In [ ]:
score = clf.score(X_train,Y_train)
print("Training Accuracy:", score)
test_score = clf.score(X_test, Y_test)
print("Test Accuracy:", test_score)

Training Accuracy: 1.0
Test Accuracy: 0.0


In [ ]:
predict = clf.predict(X_test)
print(classification_report(Y_test, predict, zero_division=0))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00       1.0
           5       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

