In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.svm import SVC
from google.colab import files

In [2]:
from google.colab import files
uploaded = files.upload()

Saving suicide rates.csv to suicide rates.csv


In [3]:
df = pd.read_csv('suicide rates.csv')
df.dropna(inplace =True)
print(df.head())

       Country          Sex   80_above   70to79   60to69    50to59 
0  Afghanistan   Both sexes       42.0     11.0       5.5       5.6
1  Afghanistan         Male       70.4     20.9       9.8       9.3
2  Afghanistan       Female       20.1      2.3       1.4       1.6
3      Albania   Both sexes       16.3      8.3       6.0       7.8
4      Albania         Male       23.2     11.9       8.1      11.4


In [4]:
df = np.array(df)
X = df[:,2:]
print(X)

[[42.0 11.0 5.5 5.6]
 [70.4 20.9 9.8 9.3]
 [20.1 2.3 1.4 1.6]
 ...
 [205.7 81.5 41.3 29.4]
 [285.0 111.5 62.8 47.0]
 [152.4 59.4 26.4 16.0]]


In [5]:
Y = df[:,1]
print(Y)

[' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' Female' ' Both sexes' ' Male' ' Female'
 ' Both sexes' ' Male' ' 

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=7)
print(X_test)

[[25.9 19.0 12.2 14.2]
 [6.0 3.7 3.0 3.3]
 [75.9 44.2 32.7 34.2]
 [205.7 81.5 41.3 29.4]
 [13.6 11.4 9.1 8.6]
 [45.3 11.8 10.5 9.4]
 [15.7 13.5 8.1 8.7]
 [28.9 20.3 12.9 11.2]
 [16.3 8.3 6.0 7.8]
 [13.6 18.9 13.3 10.9]
 [107.3 37.5 30.3 29.3]
 [26.6 21.0 11.7 6.9]
 [60.1 33.6 21.9 15.8]
 [8.0 2.9 1.5 1.2]
 [2.5 4.1 4.1 6.2]
 [42.0 25.3 17.9 13.0]
 [38.9 34.4 26.1 26.3]
 [44.4 50.2 28.9 28.6]
 [26.6 15.7 11.7 8.8]
 [27.6 22.3 23.5 24.8]
 [9.4 7.9 8.2 9.8]
 [18.5 7.9 4.6 3.3]
 [37.0 20.6 15.7 13.9]
 [26.1 28.6 13.1 9.3]
 [28.7 17.1 13.8 18.9]
 [202.6 123.2 67.3 45.5]
 [0.0 0.0 0.0 0.0]
 [45.8 17.9 12.1 8.0]
 [10.1 5.6 3.0 3.1]
 [83.8 49.4 29.7 24.5]
 [130.7 74.0 41.7 25.0]
 [10.4 7.0 4.1 3.0]
 [47.3 28.7 18.1 16.8]
 [19.7 11.3 13.0 20.8]
 [7.4 4.8 4.8 5.0]
 [3.5 3.1 2.2 1.7]
 [210.4 133.7 69.9 56.9]
 [70.8 40.5 27.7 18.7]
 [138.1 85.6 43.5 30.4]
 [20.1 6.7 6.2 9.0]
 [20.2 13.6 8.2 8.1]
 [14.5 17.4 15.6 20.0]
 [11.6 12.3 8.1 6.0]
 [4.3 2.1 1.2 1.0]
 [21.8 10.2 7.8 4.5]
 [78.5 50.5 27.8 15

In [7]:
clf = SVC(kernel="linear",C=1)
clf.fit(X_train,Y_train)

SVC(C=1, kernel='linear')

In [8]:
print(X_train.shape)
print(X_train[:5])

(439, 4)
[[37.6 21.2 23.3 25.8]
 [5.4 2.3 1.5 1.4]
 [46.7 35.2 30.8 37.7]
 [285.0 111.5 62.8 47.0]
 [36.2 28.3 21.0 24.5]]


In [9]:
clf.fit(X_train, Y_train)
print(clf.predict([[15.8, 11.6, 10, 9.5]]))

[' Female']


In [10]:
score = clf.score(X_train,Y_train)
print("Training Accuracy:", score)
test_score = clf.score(X_test, Y_test)
print("Test Accuracy:", test_score)

Training Accuracy: 0.5694760820045558
Test Accuracy: 0.5636363636363636


In [11]:
predict = clf.predict(X_test)
print(classification_report(Y_test, predict))

              precision    recall  f1-score   support

  Both sexes       0.44      0.44      0.44        34
      Female       0.57      0.74      0.64        39
        Male       0.72      0.49      0.58        37

    accuracy                           0.56       110
   macro avg       0.58      0.56      0.56       110
weighted avg       0.58      0.56      0.56       110

